Modules Release 4.8.0 (2021-07-14)
DCC-SW: Added modules (2023-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/12.3.0 compiler (requested)
DCC-SW: Released modules (2023-aug/XeonE5-2660v3)
DCC-SW: Added modules (2020-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/9.3.0 compiler
Loading python/3.8.5
  Loading requirement: build-tools/1.0 gcc/9.3.0 zlib/1.2.11 expat/2.2.0
    libffi/3.3
Loading scalapack/2.1.0
  Loading requirement: numactl/2.0.12 libxml2/2.9.10 hwloc/2.2.0 knem/1.1.4
    ucx/1.8.1 openmpi/4.0.4
rank=00 L0: Traceback (most recent call last):
rank=00 L1:   File "soc.py", line 62, in <module>
rank=00 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=00 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=00 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=00 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=00 L6:     for ibz_index, ibzwf in ibzwfs:
rank=00 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=00 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=00 L9: ValueError: could not broadcast input array from shape (116,132) into shape (116,264)
rank=06 L0: Traceback (most recent call last):
rank=06 L1:   File "soc.py", line 62, in <module>
rank=06 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=06 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=06 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=06 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=06 L6:     for ibz_index, ibzwf in ibzwfs:
rank=06 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=06 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=06 L9: ValueError: could not broadcast input array from shape (116,132) into shape (116,264)
GPAW CLEANUP (node 6): <class 'ValueError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 0): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=03 L0: Traceback (most recent call last):
rank=03 L1:   File "soc.py", line 62, in <module>
rank=03 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=03 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=03 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=03 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=03 L6:     for ibz_index, ibzwf in ibzwfs:
rank=03 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=03 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=03 L9: ValueError: could not broadcast input array from shape (116,132) into shape (116,264)
GPAW CLEANUP (node 3): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=12 L0: Traceback (most recent call last):
rank=12 L1:   File "soc.py", line 62, in <module>
rank=12 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=12 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=12 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=12 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=12 L6:     for ibz_index, ibzwf in ibzwfs:
rank=12 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=12 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=12 L9: ValueError: could not broadcast input array from shape (116,132) into shape (116,264)
rank=09 L0: Traceback (most recent call last):
rank=09 L1:   File "soc.py", line 62, in <module>
rank=09 L2:     en_soc = soc_eigenstates(calc=calc, projected=True, theta=theta, phi=phi,
rank=09 L3:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 520, in soc_eigenstates
rank=09 L4:     bzwfs = soc_eigenstates_raw(ibzwfs,
rank=09 L5:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 370, in soc_eigenstates_raw
rank=09 L6:     for ibz_index, ibzwf in ibzwfs:
rank=09 L7:   File "/zhome/87/8/147075/venv-name/gpaw/gpaw/spinorbit.py", line 442, in extract_ibz_wave_functions
rank=09 L8:     projections.matrix.array[:] = P1_nI[n1:n2]
rank=09 L9: ValueError: could not broadcast input array from shape (116,132) into shape (116,264)
GPAW CLEANUP (node 9): <class 'ValueError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 12): <class 'ValueError'> occurred.  Calling MPI_Abort!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 42.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[n-62-28-28:26486] PMIX ERROR: UNREACHABLE in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193
[n-62-28-28:26486] PMIX ERROR: UNREACHABLE in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193
[n-62-28-28:26486] PMIX ERROR: UNREACHABLE in file ../../../../../../../opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193
[n-62-28-28:26486] 4 more processes have sent help message help-mpi-api.txt / mpi-abort
[n-62-28-28:26486] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
